// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bgcExecuteInternal
int bgcExecuteInternal(CharacterVector argv, StringVector iniFiles, int simYearsOverride);
RcppExport SEXP _BiomeBGCR_bgcExecuteInternal(SEXP argvSEXP, SEXP iniFilesSEXP, SEXP simYearsOverrideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type argv(argvSEXP);
    Rcpp::traits::input_parameter< StringVector >::type iniFiles(iniFilesSEXP);
    Rcpp::traits::input_parameter< int >::type simYearsOverride(simYearsOverrideSEXP);
    rcpp_result_gen = Rcpp::wrap(bgcExecuteInternal(argv, iniFiles, simYearsOverride));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BiomeBGCR_bgcExecuteInternal", (DL_FUNC) &_BiomeBGCR_bgcExecuteInternal, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_BiomeBGCR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
