# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Execute BGC from R
#'
#' @param argv commandline arguments to pass to bgc
#' @param iniFiles a vector of paths to the individual input `ini` files
#' @param simYearsOverride the number of years to use during simulation.  if <= 0, the field "number of simulation years" from the ini file is used
#'
#' @return an integer error code (0 means no error)
bgcExecuteInternal <- function(argv, iniFiles, simYearsOverride) {
    .Call('_BiomeBGCR_bgcExecuteInternal', PACKAGE = 'BiomeBGCR', argv, iniFiles, simYearsOverride)
}

